/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PIO10_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO10_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO114_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO114_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO115_DIGIMODE_DIGITAL 0x01u /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO115_FUNC_ALT0 0x00u        /*!<@brief Selects pin function.: Alternative connection 0. */
#define PIO11_DIGIMODE_DIGITAL 0x01u  /*!<@brief Select Analog/Digital mode.: Digital mode. */
#define PIO11_FUNC_ALT0 0x00u         /*!<@brief Selects pin function.: Alternative connection 0. */

/*! @name PIO1_1 (number 15), J1[15]/P1_1-FC5_SSEL2
  @{ */
#define BOARD_INITPINS_S2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_S2_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_S2_PIN 1U    /*!<@brief 1U pin index: 1 */
                                    /* @} */

/*! @name PIO1_15 (number 62), J1[17]/P1_15-SCTO5-FC7_CTS
  @{ */
#define BOARD_INITPINS_D1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_D1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_D1_PIN 15U   /*!<@brief 1U pin index: 15 */
                                    /* @} */

/*! @name PIO1_14 (number 57), J2[1]/P1_14-SCTO7
  @{ */
#define BOARD_INITPINS_D2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_D2_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_D2_PIN 14U   /*!<@brief 1U pin index: 14 */
                                    /* @} */

/*! @name PIO1_0 (number 14), J2[3]/P1_0-PDM0_DATA-CT32B3_MAT1
  @{ */
#define BOARD_INITPINS_S1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_S1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_S1_PIN 0U    /*!<@brief 1U pin index: 0 */
                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
